name = "peripherals-push"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
FIREBASE_PROJECT_ID = "planetdrugstore-peripher-d24c0"
APP_ORIGIN = "https://planetdrugstoreconsole.web.app"
APP_URL = "https://planetdrugstoreconsole.web.app/47fto0gim6"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "PUSH_SUBSCRIPTIONS"
id = "e99801d2972d488c882ab33663479b16"